a = input('digite algo')
print('o tipo primitivo deste valor é',type(a))
print('só tem espaços?',a.isspace())
print('é um número?', a.isnumeric())
print('é alfabetico', a.isalpha())
print('é alfanumerico?', a.isalnum())
print('esta em maiuscula', a.isupper())
print("esta menuscula?", a.islower())
print('esta capitalizada?', a.istitle())

